### ISSUE TITLE
Feedback to resolve

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#916] opened 2024-11-11 19:16 UTC
## What

@murrlipp provided feedback to #870 and I have moved content style guide specific feedback to this ticket. This task is to work through the below feedback points.

- [x] Nav item title 'Style guide' and the page title / H1 'Content style guide' are different.
- [x] Vertical spacing between the two rows of alphabet jump links seems a little large. It looks larger than the spacing between the introductory text and the first line of alphabet jump links.
- [ ] If we have jump links, should we consider a 'back to top' link? GOV don't on their style guide, but they don't have jump links.
- [ ] These links render as a long list in mobile, which would make it an even longer scroll back to the top.
- [x] 'Disabled' jump link contrast is 1.94:1 so fails WCAG AA. I think because of the size it would need to 4.5:1 to pass.
- [x] Is the target area of the jump links sufficient? I can't find anything on WCAG about this specifically beyond advice from webaim [here](https://webaim.org/techniques/hypertext/link_text#link_length:~:text=The%20danger%20in,the%20wrong%20link.).

## Why
Feedback needs to be reviewed and addressed.

## Who needs to be involved
- Interaction Designer
- Content Designer
- Developer

## Done
When the feedback has been reviewed and actioned or responded to.

**Comment by murrlipp** [comment] 2024-11-12 08:40
Suggestions for everything except 'back to top' treatment. Noting here to discuss with @chrispymm later today.
 
- Suggest left and right padding of 12px on `.moj-sub-navigation__link` to increase target area.
- Spacing between subnav item lines appears to be caused by disabled jump links having 20px extra bottom padding. Suggest we remove this.
- Suggested colour for disabled jump links: `#707273`.

**Comment by murrlipp** [comment] 2024-11-29 17:13
@chrispymm I've just committed changes that cover all points except those about the 'back to top' links. Shall we get together next week to discuss these?

**Comment by murrlipp** [comment] 2024-12-02 15:08
Spoke with @chrispymm and agreed that if @helennickols was happy an accordion might help users navigate this content better.

Using an accordion addresses all of the points in this ticket.  @helennickols is happy for an accordion to be used so this has been committed to the branch.

**Closed** 2024-12-02 15:08 UTC
